// api/booky-send.js — daily Booky reminder (personalized per subscriber).
// Triggered by Vercel Cron (see vercel.json) once a day.
//
// Flow:
//   1. Verify the request came from Vercel Cron (Bearer ${CRON_SECRET})
//   2. Fetch all active subscribers from Resend audience
//   3. Send each subscriber a personalized email showing their streak
//
// Streak is stored in contact.first_name as a string number (internal only).
//
// Env vars:
//   RESEND_API_KEY          — sk_xxx from resend.com/api-keys
//   RESEND_AUDIENCE_ID      — uuid from resend.com/audiences
//   RESEND_FROM             — verified sender, e.g. "Booky <booky@90books.com>"
//   CRON_SECRET             — random string, Vercel auto-attaches as Bearer

const { unsubscribeUrl, unsubscribeHeaders } = require('../lib/unsubscribe');
const { maySend, sendDateKey } = require('../lib/daily-trigger');

// ---- One-off notes, keyed by the UTC date of the send ----
//
// ⚠️ THIS MECHANISM SILENTLY FAILED AND IS NOT TRUSTED. Do not use it to
// announce anything until it is root-caused. On 2026-08-07 a note keyed
// '2026-08-07' did not appear in that evening's email. Everything checked out
// and it still did not send: the deployed source on the live-aliased deployment
// contained the key, that deployment was production at 23:00 UTC, the send went
// out at 23:16 UTC (so `toISOString().slice(0,10)` was '2026-08-07'), and
// book-recs-app is definitely the sender — booky-deploy has no Resend key and
// 500s. The raw message source showed the note block simply absent, meaning
// `updateNote` was null at runtime. Unexplained.
//
// The gap that let it ship: `buildHtml` was verified locally, which proves
// nothing about what the deployed cron emits. There is no way to see a rendered
// email without sending to the whole audience, so a failure here is invisible
// until subscribers get the wrong thing.
//
// Announcements now go out as a Resend Broadcast instead (composed and sent from
// the dashboard, visible before it sends). See scripts/create-broadcast.mjs.
//
// That preview mode now exists (see `?preview=1` below), so a note here can be
// checked against the DEPLOYED endpoint before the cron sends it. Never add a
// note without running that check — it is the only thing standing between a
// typo and ~140 inboxes.
const UPDATE_NOTES = {
  // Answers suggestion #2 from Beginning_Alps_1817 in the r/B00KY "Game Updates"
  // thread: they asked for a wider list because you often burn a guess on a word
  // you know is wrong just to place a letter. Retry of the 2026-08-07 note that
  // silently did not send. Subreddit is B00KY with ZEROS, not letter O.
  '2026-08-08': {
    title: 'You asked for a bigger word list',
    body: `You often burn a guess on a word you know is wrong, just to place a letter. Now those land: the word list went from about 10,000 to 18,483. More ideas? Drop them in the <a href="https://www.reddit.com/r/B00KY/comments/1uh88g6/game_updates/" style="color:#c8398f;text-decoration:none;font-weight:600;">r/B00KY game updates thread</a>.`,
  },
};

module.exports = async (req, res) => {
  // ---- Preview: render the email without sending anything ----
  //
  // Deliberately BEFORE the auth check and unauthenticated, so the deployed
  // output can be inspected with a plain curl. That is the whole point: this
  // email is generated by a cron at send time, so before this existed the only
  // way to see what it produces was to send it to every subscriber. A note that
  // silently failed to render on 2026-08-07 was invisible until it landed wrong.
  //
  // Safe to leave open: it sends nothing, reads no contacts, never calls Resend,
  // and returns the same template subscribers already receive. There is no
  // subscriber data in it — `streak` is a number you pass in yourself.
  //
  //   curl 'https://90books.com/api/booky-send?preview=1'
  //   curl 'https://90books.com/api/booky-send?preview=1&date=2026-08-08&streak=7'
  //
  if (req.query && req.query.preview) {
    const dateParam = typeof req.query.date === 'string' ? req.query.date : null;
    // Model the real fire time (23:00 UTC) so the date key matches the send.
    const at = dateParam ? new Date(`${dateParam}T23:00:00Z`) : new Date();
    const key = sendDateKey(at);
    const streak = parseInt(req.query.streak, 10) || 0;
    const hasStreak = streak >= 2;

    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.setHeader('Cache-Control', 'no-store');
    res.setHeader('X-Booky-Date-Key', key);
    res.setHeader('X-Booky-Has-Note', UPDATE_NOTES[key] ? 'yes' : 'no');
    res.status(200).send(buildHtml({
      subject:  hasStreak ? `🔥 Day ${streak} — don't lose it now` : `Today's Booky is ready 📚`,
      headline: hasStreak ? `Your 🔥${streak}-day streak is waiting.` : `Today's word is waiting.`,
      subline:  hasStreak ? `Six guesses. Don't break your ${streak}-day streak.` : `Six guesses. Don't break the streak.`,
      today: formatSendDate(key),
      playUrl: 'https://90books.com/booky?utm_source=reminder_email&utm_medium=email&utm_campaign=daily_reminder',
      updateNote: UPDATE_NOTES[key] || null,
      // Signed for a placeholder address, so the preview shows the real link
      // shape without exposing a working link for anyone on the list.
      unsubUrl: unsubscribeUrl('preview@90books.com'),
    }));
    return;
  }

  // ---- Trigger: what actually drives the daily send now ----
  //
  // Vercel Cron is DISABLED for this project. Its registration froze pinned to a
  // 2026-07-15 deployment, so every reminder for a month was built by month-old
  // code — dead unsubscribe link, missing update notes — while 90books.com
  // served current code. Changing the schedule, deleting the crons block, and
  // disabling + redeploying all failed to move the pin.
  //
  // `booky-health.yml` already runs scripts/health-live.mjs at 23:17 UTC daily,
  // and that script is what calls this now. Unauthenticated on purpose: that
  // Actions job has no CRON_SECRET in scope and adding one needs a workflow
  // change that cannot be pushed from a session. What makes it safe is
  // lib/daily-trigger.js — a 21:00-04:00 UTC window plus a once-per-day Redis
  // lock that fails CLOSED. Read that file before touching any of this.
  if (req.query && req.query.trigger) {
    const gate = await maySend();
    if (!gate.go) {
      console.log('[booky-send] trigger skipped —', gate.reason);
      res.status(200).json({ ok: true, sent: 0, skipped: gate.reason, dateKey: gate.dateKey });
      return;
    }
    console.log('[booky-send] trigger accepted for', gate.dateKey);
    // owns today's send — falls through to the send below
  } else {
    // ---- Auth: Vercel Cron, or manual via x-debug-key=CRON_SECRET ----
    const CRON_SECRET = process.env.CRON_SECRET;
    if (CRON_SECRET) {
      const auth = req.headers.authorization || '';
      const debugKey = req.headers['x-debug-key'] || '';
      const ok = auth === `Bearer ${CRON_SECRET}` || debugKey === CRON_SECRET;
      if (!ok) {
        res.status(401).json({ error: 'unauthorized' });
        return;
      }
    }
  }

  const RESEND_API_KEY     = process.env.RESEND_API_KEY;
  const RESEND_AUDIENCE_ID = process.env.RESEND_AUDIENCE_ID;
  const RESEND_FROM        = process.env.RESEND_FROM || 'Booky <booky@90books.com>';

  if (!RESEND_API_KEY || !RESEND_AUDIENCE_ID) {
    console.error('[booky-send] Resend env not configured');
    res.status(500).json({ error: 'Resend not configured' });
    return;
  }

  // UTM-tagged so PostHog attributes return plays to the daily reminder email.
  const playUrl = 'https://90books.com/booky?utm_source=reminder_email&utm_medium=email&utm_campaign=daily_reminder';
  // The day this send BELONGS to, which is not the same as the wall-clock UTC
  // day it happens to run on. sendDateKey() rolls back to the previous date
  // before 04:00 UTC, exactly as the trigger's once-per-day lock does.
  //
  // Getting this from `new Date()` was a real bug: on 2026-08-15 the 21:17 UTC
  // health run landed at 21:35 — BEFORE the window opened — so the backup slot
  // sent at 01:57 UTC the next morning, and `new Date()` rendered
  // "Sunday, August 16" in an email that reached Eastern readers at 9:57pm on
  // SATURDAY, pointing at a word their board would not show until the next day.
  // The queue rolls at each player's LOCAL midnight (booky/app.js
  // computeDayNumber), so the send key is the only date that matches the board.
  const dateKey    = sendDateKey();
  const today      = formatSendDate(dateKey);
  const updateNote = UPDATE_NOTES[dateKey] || null;

  // ---- 1. Fetch all active subscribers ----
  let subscribers = [];
  try {
    const r = await fetch(
      `https://api.resend.com/audiences/${RESEND_AUDIENCE_ID}/contacts`,
      { headers: { Authorization: `Bearer ${RESEND_API_KEY}` } }
    );
    if (!r.ok) {
      const txt = await r.text();
      console.error('[booky-send] failed to fetch contacts', r.status, txt);
      res.status(500).json({ error: 'failed to fetch contacts', detail: txt });
      return;
    }
    const data = await r.json();
    subscribers = (data.data || []).filter(c => !c.unsubscribed);
  } catch (err) {
    console.error('[booky-send] fetch contacts exception:', err);
    res.status(500).json({ error: 'exception fetching contacts', detail: String(err) });
    return;
  }

  if (subscribers.length === 0) {
    console.log('[booky-send] no active subscribers, nothing to send');
    res.status(200).json({ ok: true, sent: 0 });
    return;
  }

  // ---- 2. Send personalized email to every subscriber ----
  //
  // BATCHED, not one POST per contact. Resend allows 10 requests per second
  // per team, and the old loop fired one unthrottled POST /emails per
  // subscriber with no retry. The result, every single night:
  //
  //   2026-08-14  sent 129, FAILED 49   429 rate_limit_exceeded
  //   2026-08-15  sent 138, FAILED 50   429 rate_limit_exceeded
  //
  // Roughly a quarter of the list silently got no reminder at all, and it was
  // invisible because health-live.mjs only warned — the workflow run stayed
  // green, so no alarm mail ever went out.
  //
  // POST /emails/batch carries up to 100 fully-personalized messages in ONE
  // request, so the list is 2 requests instead of 188, and it keeps the two
  // things this email cannot lose: per-contact `headers` (the signed
  // List-Unsubscribe, see lib/unsubscribe.js) and `tags`. Only `attachments`
  // is unsupported on batch, and this email has none. It also stops the send
  // being a race against the function timeout as the list grows.
  const messages = subscribers.map((contact) => {
    // streak stored in first_name as a string (set by booky-subscribe + booky-update-streak)
    const streak = parseInt(contact.first_name, 10) || 0;
    const hasStreak = streak >= 2;

    const subject = hasStreak
      ? `🔥 Day ${streak} — don't lose it now`
      : `Today's Booky is ready 📚`;

    const headline = hasStreak
      ? `Your 🔥${streak}-day streak is waiting.`
      : `Today's word is waiting.`;

    const subline = hasStreak
      ? `Six guesses. Don't break your ${streak}-day streak.`
      : `Six guesses. Don't break the streak.`;

    return {
      from: RESEND_FROM,
      to: contact.email,
      // Deliberately NO reply_to. Replies go to the From address,
      // booky@90books.com, which is the address players already recognise on
      // the daily reminder. They reach Olga because the domain forwards
      // *@90books.com to her inbox, so routing them to hello@ would only make
      // the reply look like it came from somewhere else.
      subject,
      // Per-contact signed link. Resend's {{{RESEND_UNSUBSCRIBE_URL}}} only gets
      // substituted for Broadcasts — this endpoint sends per-contact, where it
      // shipped as a literal dead href. See lib/unsubscribe.js.
      html: buildHtml({
        subject, headline, subline, today, playUrl, updateNote,
        unsubUrl: unsubscribeUrl(contact.email),
      }),
      headers: unsubscribeHeaders(contact.email),
      tags: [{ name: 'type', value: 'booky-daily' }],
    };
  });

  let sent = 0;
  let failed = 0;

  for (const chunk of chunk100(messages)) {
    if (await resendPost('https://api.resend.com/emails/batch', chunk, RESEND_API_KEY)) {
      sent += chunk.length;
    } else {
      // The batch as a whole did not go. Retry its members one at a time so a
      // single unsendable address costs one subscriber and not the other 99.
      console.error('[booky-send] batch of', chunk.length, 'failed — retrying per-contact');
      for (const msg of chunk) {
        if (await resendPost('https://api.resend.com/emails', msg, RESEND_API_KEY)) {
          sent++;
        } else {
          failed++;
          console.error('[booky-send] gave up on', msg.to);
        }
        await sleep(120); // 8/s, under the 10/s ceiling
      }
    }
    await sleep(150); // ditto, between batches
  }

  console.log(`[booky-send] done — sent: ${sent}, failed: ${failed}`);
  res.status(200).json({ ok: true, sent, failed, total: subscribers.length });
};

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function* chunk100(arr) {
  for (let i = 0; i < arr.length; i += 100) yield arr.slice(i, i + 100);
}

// POST to Resend that survives the 10 req/s ceiling.
//
// A 429 is not a delivery failure, it means "come back in a moment" — treating
// it as one is what dropped ~50 subscribers a night. So 429 and 5xx are retried
// with backoff; any other 4xx is a request this code will never get right by
// repeating it, so it stops immediately rather than burning the clock.
async function resendPost(url, payload, apiKey, attempts = 4) {
  for (let i = 0; i < attempts; i++) {
    try {
      const r = await fetch(url, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });
      if (r.ok) return true;

      const txt = await r.text();
      console.error('[booky-send]', r.status, url, txt.slice(0, 300));
      if (!(r.status === 429 || r.status >= 500) || i === attempts - 1) return false;

      // Resend returns `retry-after` in seconds on a 429; back off if it does
      // not, so a retry storm cannot become the reason for the next 429.
      const after = parseFloat(r.headers.get('retry-after') || '0');
      await sleep(after > 0 ? after * 1000 : 500 * 2 ** i);
    } catch (err) {
      console.error('[booky-send] exception on', url, err);
      if (i === attempts - 1) return false;
      await sleep(500 * 2 ** i);
    }
  }
  return false;
}

// Renders a YYYY-MM-DD send key as "Saturday, August 15" for the email's date
// line. Anchored at midday UTC so no timezone can nudge it onto the neighbouring
// day — the whole point is that this string matches the send key exactly.
function formatSendDate(key) {
  return new Date(`${key}T12:00:00Z`).toLocaleDateString('en-US', {
    weekday: 'long', month: 'long', day: 'numeric', timeZone: 'UTC',
  });
}

function buildHtml({ subject, headline, subline, today, playUrl, updateNote, unsubUrl }) {
  // Sits below the play button so the reminder's primary CTA still comes first.
  const noteBlock = updateNote ? `
        <tr><td style="padding-top:28px;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#fdf2f9;border:1px solid #f0d8ea;border-radius:10px;padding:18px 20px;">
            <tr><td>
              <p style="margin:0 0 6px;font-size:10px;letter-spacing:2px;text-transform:uppercase;color:#c8398f;font-weight:700;">Game update</p>
              <p style="margin:0 0 8px;font-size:15px;line-height:1.45;color:#2a0a26;font-weight:600;">${updateNote.title}</p>
              <p style="margin:0;font-size:13px;line-height:1.6;color:#6a4a6c;">${updateNote.body}</p>
            </td></tr>
          </table>
        </td></tr>` : '';

  return `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>${subject}</title></head>
<body style="margin:0;padding:0;background:#fff8fb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Inter,sans-serif;color:#2a0a26;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#fff8fb;padding:40px 16px;">
    <tr><td align="center">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:480px;background:#ffffff;border:1px solid #ead4e2;border-radius:14px;padding:32px 28px;">
        <tr><td align="center">
          <img src="https://90books.com/logo/booky-email.png" width="132" height="51" alt="Booky" style="display:block;margin:0 auto 4px;border:0;outline:none;text-decoration:none;">
          <p style="margin:0 0 24px;color:#a587a9;font-size:11px;letter-spacing:2.5px;text-transform:uppercase;">${today}</p>
          <p style="margin:0 0 12px;font-size:18px;line-height:1.5;color:#2a0a26;font-weight:600;">${headline}</p>
          <p style="margin:0 0 24px;font-size:14px;line-height:1.5;color:#6a4a6c;">${subline}</p>
          <a href="${playUrl}" style="display:inline-block;background:linear-gradient(135deg,#c8398f,#9a2670);color:#ffffff;text-decoration:none;font-weight:600;padding:13px 28px;border-radius:10px;font-size:15px;">Play today's Booky →</a>
        </td></tr>${noteBlock}
        <tr><td align="center" style="padding-top:24px;">
          <p style="margin:0;font-size:13px;line-height:1.5;color:#6a4a6c;">
            Know a reader who'd love this? Send them <a href="https://90books.com/booky?utm_source=reminder_email&utm_medium=email&utm_campaign=friend_referral" style="color:#c8398f;text-decoration:none;">90books.com/booky</a>
          </p>
        </td></tr>
        <tr><td align="center" style="padding-top:32px;">
          <p style="margin:0;font-size:11px;color:#a587a9;line-height:1.5;">
            Booky by 90books · you signed up for daily reminders at <a href="${playUrl}" style="color:#c8398f;text-decoration:none;">90books.com/booky</a>.<br>
            <a href="${String(unsubUrl).replace(/&/g, '&amp;')}" style="color:#a587a9;text-decoration:underline;">Unsubscribe</a>
          </p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}
